export const activities: Activity[] = [
  {
    _id: "1",
    type: "project",
    name: "Project created",
    description: "Project A created",
    createdAt: new Date().toISOString(),
    link: "/projects/1",
    status: "project-create",
  },
  {
    _id: "2",
    type: "project",
    name: "Project removed",
    description: "Project B removed",
    createdAt: new Date().toISOString(),
    link: "",
    status: "project-delete",
  },
  {
    _id: "3",
    type: "project",
    name: "Collab add",
    description: "Someone add collaborator to project A",
    createdAt: new Date().toISOString(),
    link: "/projects/1",
    status: "collaborator-add",
  },
  {
    _id: "4",
    type: "project",
    name: "Collab remove",
    description: "Someone remove collaborator from project A",
    createdAt: new Date().toISOString(),
    link: "/projects/1",
    status: "collaborator-remove",
  },
  {
    _id: "5",
    type: "test-case",
    name: "Test failed",
    description: "Test case #44 failed",
    createdAt: new Date().toISOString(),
    link: "/projects/1",
    status: "test-fail",
  },
  {
    _id: "6",
    type: "test-case",
    name: "Comment",
    description: "Someone commented in the project A",
    createdAt: new Date().toISOString(),
    link: "/projects/1",
    status: "comment",
  },
  {
    _id: "7",
    type: "test-case",
    name: "Test passed",
    description: "Test case #63 passed",
    createdAt: new Date().toISOString(),
    link: "/projects/1",
    status: "test-pass",
  },
  {
    _id: "8",
    type: "test-case",
    name: "Mentioned",
    description: "Someone mentioned you in project A",
    createdAt: new Date().toISOString(),
    link: "/projects/1",
    status: "mentioned",
  },
];
